openapi: 3.0.3

info:
  title: API управления финансовыми аккаунтами
  description: >
    Учебный API управления финансовыми аккаунтами.
    Аккаунт имеет уникальный текстовый идентификатор, имя владельца,
    баланс (количество денег) и статус (активный/неактивный).
    API позволяет осуществлять CRUD операции с аккаунтом.
  version: "1.0"

servers:
  - url: http://localhost:9090

paths:
  /account/:
    get:
      operationId: GetAccounts
      description: Получение списка аккаунтов
      responses:
        '200':
          description: Успешное получение списка

